### ISSUE TITLE
BASIS Continuous Integration

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#294]
Add continuous integration to BASIS so failed test cases can be reported automatically.

Travis-ci is known to work well with github: https://travis-ci.org/profile

**Comment by ahundt** [comment]
We should probably do this too to avoid issues

**Comment by ahundt** [comment]
https://stackoverflow.com/questions/30404594/how-to-test-both-python-and-c-in-one-travis-yml-without-running-the-c-multi

**Comment by schuhschuh** [comment]
I'll have a look.

**Comment by schuhschuh** [comment]
The build is passing now, just the tests need fixing.
