### ISSUE TITLE
Typo on website getting help page

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#379]
It looks like there is a [typo on the website](http://opensource.andreasschuh.com/cmake-basis/help.html) because the text `orphan:` appears to be present:
![orphan basis help](https://cloud.githubusercontent.com/assets/55744/2724253/ec6d7190-c59e-11e3-8e7e-0c8c40c57ae6.png)

**Comment by schuhschuh** [comment]
I just figured that the .rst files that are explicitly included in other .rst files should be excluded using the ```EXCLUDE_PATTERN``` option of ```basis_add_sphinx_doc```. No need for the orphan field and this also fixes some other "duplicate label" warnings.
