### ISSUE TITLE
Broken quick start guide steps

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#380]
This:

    export PATH="~/local/bin:${PATH} "

should be:

    export PATH=${PATH}:~/local/bin/

(I'll add more as they come up)

I've also created a slightly improved quick start script located at:
https://gist.github.com/ahundt/5fa3a801db2aa09693f9

**Comment by schuhschuh** [comment]
I disagree with the order of the PATH. The quick start installation directory should be preferred.

**Comment by ahundt** [comment]
I think I ran into a conflict and that's why I changed it.

**Comment by ahundt** [comment]
I believe versions of the libraries installed on the system were picked up perhaps instead of the ones included in basis? sorry I don't remember well. does the script work at the moment?

**Comment by schuhschuh** [comment]
I am about to run it, but if there was a problem I doubt it was because of the PATH order. With the suggested reversed order, the ```basisproject``` tool of possibly another installation might be used...

**Comment by schuhschuh** [comment]
Just needed small modifications. There might be a problem in BASIS when the CMAKE_INSTALL_PREFIX argument is a relative path... so the script makes sure it's absolute.

**Comment by schuhschuh** [comment]
Besides on my OS X, the script run without issues on a fresh Ubuntu 14.04 installation (after installing the build prerequisites).
