### ISSUE TITLE
bash utilities 'import' fails when module has '.sh' extension

### ISSUE THREAD

**Issue by psuggs** [schuhschuh/cmake-basis#383]
When using the 'import' function, if the module name specified has a '.sh' extension specified it will fail to be found because the (.) in this case is not given special consideration before it is replaced by forward slashes resulting in a module name to be tested for as "name/sh.sh" instead of "name.sh"

**Comment by schuhschuh** [comment]
> It wasn't obvious that the extension not be specified.  I got my interpretation from the documentation statement:
	Moreover, the <tt>.sh</tt> extension of the modules is appended to the module name if not specified.
To me, this reads that all modules /must/ have an ".sh" extension though it's specification is optional when invoking the import function.  I would think a documentation update would be sufficient to address future confusion given that you say that the intent is that the specification is actually not optional but should actually not be present.

After having a look now at the implementation, I decided to rather clarify the documentation. Making the ".sh" extension optional would result in ambiguities when a module file is named "sh.sh".
