### ISSUE TITLE
bash utilities 'realpath' behavior question

### ISSUE THREAD

**Issue by psuggs** [schuhschuh/cmake-basis#384]
What is the expected return of the following:
    `realpath /root/bin/slim`
when
    `/root/bin/slim` symlink-to `/opt/slim/bin/slim`
    `/opt/slim/` symlink-to `/opt/slim-0.61/`

I expected `/opt/slim-0.61/bin/slim` but get `/opt/slim/bin/slim`.  In this scenario is it expected that realpath would resolve all symlinks or are there situations when it is expected not to?

bash 3.2

**Comment by schuhschuh** [comment]
Wow, sorry for missing your response. In this case I would agree that the Bash function should return the same value. I'll try to reproduce the issue and fix it finally if possible.

**Comment by schuhschuh** [comment]
The issue was caused by a wrong order of operations. Replacing the file directory by the output of ```pwd -P``` after the link ```/root/bin/slim``` itself was resolved to ```/opt/slim/bin/slim``` results in the expected output of ```/opt/slim-0.61/bin/slim```.
