### ISSUE TITLE
basisproject update fails because original_template argument not set

### ISSUE THREAD

**Issue by schuhschuh** [schuhschuh/cmake-basis#385]
The "basisproject update" command fails with the error that the arguments namespace does not contain an attribute named original_template. This argument is at the moment only available to the "basisproject upgrade" command.

**Comment by michelepagot** [comment]
Problem is still there. I just meet BASIS project and go through QuickStart page
I follow everything without changing a "bit"
Problem popup at: http://opensource.andreasschuh.com/cmake-basis/quickstart.html#create-an-example-project

basisproject update --root ~/local/src/hellobasis --noexample --config-settings

Here history of my commands:
$ mkdir -p ~/local/src
$ cd  ~/local/src
$  git clone https://github.com/schuhschuh/cmake-basis.git
$  cd cmake-basis/
$  mkdir BUILD && cd BUILD
$  ccmake ..
$  make
$  make install
$  export PATH="~/local/bin:${PATH} "
$  export BASIS_EXAMPLE_DIR="~/local/share/basis/example"
$  export HELLOBASIS_RSC_DIR="${BASIS_EXAMPLE_DIR}/hellobasis"
$  basisproject create --name HelloBasis --description "This is a BASIS project." --root ~/local/src/hellobasis
$  basisproject update --root ~/local/src/hellobasis --noexample --config-settings

Traceback (most recent call last):
  File "/home/michelepa/local/bin/basisproject", line 1158, in <module>
    if args.original_template:
AttributeError: 'Namespace' object has no attribute 'original_template'
