### ISSUE TITLE
Broken links and strings in default basisproject create template

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#398]
There are some broken links and strings in default basisproject create template.
For example, the "download" page when generated using basisproject create will point to something like:

    `GitHub <https://github.com/schuhschuh/cis/>`__

Instead, perhaps we should make it possible to specify a default github account name in BasisProject.cmake or in basisproject create.

There are also some instances of the string "BASIS" where it should substitute the project name, and other links scattered throughout that don't do the right thing by default.

However, some instances of BASIS are correct, because basis is a dependency and that text and those links should remain where appropriate.

**Comment by schuhschuh** [comment]
Should be fine now.
