### ISSUE TITLE
doc pdf does not have page numbers

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#399]
The table of contents on the generated pdf lists page numbers, but the page numbers are not actually on the pages, so if you actually print the manual you can't find the page you're looking for!

Also, there should be something indicating how to make a release vs beta pdf. I don't really know how that works. Also, perhaps add a way to include the exact date and time when the release pdf is generated similarly to what is included in the beta pdfs.

**Comment by schuhschuh** [comment]
Adding ```\pagestyle{plain}``` to the preamble in the Sphinx configuration file adds page numbers from the second page on.

**Comment by ahundt** [comment]
splitting the second paragraph to a separate issue, don't know why I put both in one
