### ISSUE TITLE
Install fails with python-related error message

### ISSUE THREAD

**Issue by JPGygax68** [schuhschuh/cmake-basis#416]
Using Visual Studio 2013 under Windows 8.1 to build "develop" branch.
Build is ok (after two small fixes which I intend to create a pull request for), but installation fails with the following message:

```
...
-- Up-to-date: d:/Program Files (x86)/BASIS-3.1.0/Doc/COPYING.txt
CMake Error at cmake_install.cmake:39 (file):
  file INSTALL cannot find
  "D:/SourcePackages/cmake-basis/build/src/utilities/python/CMakeFiles/utilities_python.dir/build/basis/__init__.py".
```

The message is the same whether I use Python 2.7 or 3.4.

**Comment by schuhschuh** [comment]
This seems a problem with the CMake configuration. What version of CMake are you using ? Have you downloaded/checked out the 3.1.0 release version, master, or develop branch of BASIS ? For most recent CMake versions (>=3.1), you probably would need to use the develop branch. However, I have not encountered this specific error before and it works fine on OS X. I have no access to Windows right now, but will have a look later this week.

**Comment by JPGygax68** [comment]
I started out with the master branch, using CMake 3.1. CMake configuration would run into the known bug related to "INTERFACE" properties, so I switched to the `develop` branch, which configured and generated fine. I then ran into two minor compilation errors that were easy to fix and that I've sent you a pull request for. BASIS now builds ok, but installation fails with the above message.

**Comment by schuhschuh** [comment]
@JPGygax68, sorry for the delay in getting back to this issue. I finally had a chance to take a look. Unfortunately, I only have Windows 7 (though I wouldn't expect this to make the difference) and failed yet to reproduce this installation error using CMake 3.2.1.

```
[...]
-- Installing: C:/Users/as12312/Downloads/BASIS Installation/Doc/COPYING.txt
-- Installing: C:/Users/as12312/Downloads/BASIS Installation/Lib/Python/basis/__init__.py
-- Installing: C:/Users/as12312/Downloads/BASIS Installation/Lib/Python/basis/argparse.py
[...]
```

Can you easily check if the problem still persists with the latest develop HEAD?
Do the following files exist or are they missing (I suppose the latter must be due to the error)?:
```
D:/SourcePackages/cmake-basis/build/src/utilities/python/CMakeFiles/utilities_python.dir/build___init___py.cmake
D:/SourcePackages/cmake-basis/build/src/utilities/python/CMakeFiles/utilities_python.dir/build/basis/__init__.py
```

I keep digging to see if I find the problem (at least found one issue related to the __init__.py files).

**Comment by schuhschuh** [comment]
Closing this issue due to inability to reproduce and lack of response whether issue still persists. Feel free to reopen with more details on the issue if unresolved.
