### ISSUE TITLE
Failed to determine MATLAB version (Win 7, CMake 3)

### ISSUE THREAD

**Issue by schuhschuh** [schuhschuh/cmake-basis#429]
Error message:
```
Determining MATLAB version...
CMake Error at src/cmake/MatlabTools.cmake:188 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/as12312/Downloads/cmake-basis/vs2013/CMakeFiles/MatlabVersion.txt
Call Stack (most recent call first):
  src/cmake/MatlabTools.cmake:224 (basis_get_full_matlab_version)
  src/cmake/FindMATLAB.cmake:281 (basis_get_matlab_version)
  src/cmake/CommonTools.cmake:56 (_find_package)
  src/cmake/CommonTools.cmake:367 (find_package)
  src/cmake/ProjectTools.cmake:1683 (basis_find_package)
  src/cmake/ProjectTools.cmake:1898 (basis_find_packages)
  src/cmake/ProjectTools.cmake:2156 (basis_project_begin)
  CMakeLists.txt:66 (basis_project_impl)
[...]
CMake Warning at src/cmake/ProjectTools.cmake:1935 (message):
  Failed to determine MATLAB version! Check if you can run "C:/Program
  Files/MATLAB/R2012b/bin/matlab.exe -nodesktop -nosplash -r 'version,quit
  force'" and try again.
Call Stack (most recent call first):
  src/cmake/ProjectTools.cmake:2156 (basis_project_begin)
  CMakeLists.txt:66 (basis_project_impl)
```

File ```CMakeFiles/MatlabVersion.txt``` is indeed missing. Executing the command specified in the second warning in a Command Prompt works fine. It opens a MATLAB terminal, prints the version number, and quits MATLAB. The error persists even when re-configuring the build system. It is hence different from the old issue #216.

**Comment by schuhschuh** [comment]
Besides fixing the command argument list, a wait loop is added to account for some delay between MATLAB process termination and MatlabVersion.txt file being actually written to disk (virtual machine/network FS related?). Determining the MATLAB version should be now more robust than before to these issues.

**Comment by felixvd** [comment]
I am getting almost the same error message on Windows 8.1, MATLAB R2015a and the current master build. However, the MATLAB command window does not report the version number after opening:

    Undefined function or variable 'basis_get_full_matlab_version'.

A misinterpreted function call maybe?

**Comment by schuhschuh** [comment]
You have to test the generated basis_get_full_matlab_version function by changing into the building directory which contains the corresponding .m file. Either the top level build directory or the CMakeFiles subdirectory. 

Are you using the develop branch?

The above mentioned fix is not merged into master yet.

**Comment by felixvd** [comment]
I wasn't; switching to it worked.
