### ISSUE TITLE
Where to put generators?

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#437]
I'm using google flatbuffers, which generate header files based on a protocol file. This is the same as google protocol buffers. However, if I put the protocol file generation in the /src folder, the variables set are not available in /test. If I put them in config/Settings.cmake it seems they simply do not get generated, though the variables are set.

Where can I put these files so that they are generated at the beginning and globally available?

current src:
https://github.com/ahundt/robone/blob/develop/src/CMakeLists.txt

attempted settings folder:
https://github.com/ahundt/robone/blob/feature/module_split/config/Settings.cmake

test file which does not work:
https://github.com/ahundt/robone/blob/feature/module_split/test/CMakeLists.txt

**Comment by schuhschuh** [comment]
The config/Settings.cmake file would be proper for global settings and initialisation. However, the ```flatbuffers_generate_c_headers``` function uses CMake's ```add_custom_command``` and this requires that a custom target which depends on this output must be defined in the very same ```CMakeLists.txt``` file (cf. doc of [add_custom_command](http://www.cmake.org/cmake/help/v3.2/command/add_custom_command.html))! You should define a custom target for the generation of the output right next to ```flatbuffers_generate_c_headers``` as it is also outlined in the CMake documentation.
