### ISSUE TITLE
BASIS 3.1 doesn't build on CMake 3.3 + Ubuntu 14.04

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#447]
The master branch didn't work, but the develop branch did. Perhaps we can just push out what is in devel as 3.1.1?

The issue in 3.1 was related to the use of the `BUNDLE` property.

This is also true for OS X and CMake 3.3

**Comment by schuhschuh** [comment]
Close as this question is also addressed by #451.
