### ISSUE TITLE
strerror_r() signature not correct on OS X

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#449]
need to fix a small compiler error due to strerror_r() on os x

**Comment by ahundt** [comment]
I've been using the code with this patch for a long time, so I think this is good to go

**Comment by schuhschuh** [comment]
What confuses me is that I have certainly tested this code on OS X when I modified it and according to [this doc of strerror_r](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/strerror_r.3.html), the return value is ```int```...

**Comment by schuhschuh** [comment]
How about this solution instead: http://www.club.cc.cmu.edu/~cmccabe/blog_strerror.html

**Comment by schuhschuh** [comment]
Maybe a question, what compiler are you using? When on OS X, I compile with Xcode's clang. Might be that you are using GCC?

**Comment by schuhschuh** [comment]
> according to this doc of strerror_r, the return value is int...

Hold on, that is actually in accordance with your fix ;)

**Comment by ahundt** [comment]
great :-)
