### ISSUE TITLE
Make basisproject and Python utilities compatible with Python 3

### ISSUE THREAD

**Issue by schuhschuh** [schuhschuh/cmake-basis#453]
From #450:
```
[2015.09.11:10.36][Jiri@JiriMBP:~/lib/cpp/cmake-related/basis-related]$  python --version
Python 3.4.3 :: Anaconda 2.3.0 (x86_64)
[2015.09.11:10.36][Jiri@JiriMBP:~/lib/cpp/cmake-related/basis-related]$  basisproject
  File "/usr/local/bin/basisproject", line 430
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by schuhschuh** [comment]
Useful cheat sheet: http://python-future.org/compatible_idioms.html

**Comment by ahundt** [comment]
I think there is also a converter of some sort. Make sure to retain python2 compatibility when 3 is added. I know I need to keep using python2 in my work for a while sadly.

**Comment by schuhschuh** [comment]
All Python code should now be compatible with both Python 2 and 3.

**Comment by schuhschuh** [comment]
All tests pass with BASIS either configured with Python 2.7.9 or Python 3.4.3.
