### ISSUE TITLE
pdflatex not found when building manual in Xcode

### ISSUE THREAD

**Issue by schuhschuh** [schuhschuh/cmake-basis#461]
The ```Makefile``` generated by Sphinx calls ```pdflatex```. If it is not found in the standard PATH, Xcode will not find this command. Use auxiliary script in target post-build command to fix this issue.

**Comment by ahundt** [comment]
side note: installing latex is very easy with [homebrew](http://brew.sh)

```bash
brew tap caskroom/cask # only if you don't have homebrew casks installed
brew cask install mactex
```

**Comment by schuhschuh** [comment]
Well, but that's not the problem. I have TexLive installed which is easy as well. It works fine when I build on the command line via:

```
cmake --build . --config Release --target softwaremanual_pdf
```

Even when I would install it from homebrew, Xcode would possibly not find it. Just like for Doxygen, during CMake configuration I am looking for the pdflatex command. The configured path should be used then during the build. This is currently not the case but can be done.

**Comment by ahundt** [comment]
You are correct, when I needed to generate the documentation in the past I used the make generator, xcode generation I only used with building the code itself, so I can confirm the issue.
