### ISSUE TITLE
cmake namespace support

### ISSUE THREAD

**Issue by ahundt** [schuhschuh/cmake-basis#497]
It seems cmake has added namespaces, there are a couple possible ways cmake-basis could utilize them. One idea is perhaps uids should eventually be ported to use namespaces instead, particularly when there are submodules?

**Comment by schuhschuh** [comment]
Can you link to some documentation of the respective CMake feature?

**Comment by ahundt** [comment]
https://cmake.org/cmake/help/v3.3/policy/CMP0037.html?highlight=colon

https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html?highlight=colon

perhaps it only applies to exported targets? then it may not really be what we want.

**Comment by schuhschuh** [comment]
Yes, I thought you were referring to the NAMESPACE argument of the [export](https://cmake.org/cmake/help/v3.3/command/export.html) function. This is not a replacement for the BASIS target UIDs. Note also that BASIS already exports each (sub-)project's targets with their respective NAMESPACE prefix.

Unlike CMake which now wants to establish double colons (```::```) as namespace separator, BASIS uses a single dot ```.``` and therefore disallows dots in target names. Note that CMP0037 would disallow BASIS to use a double colon for non-imported targets for the target UIDs. Hence, it's probably good we didn't choose the C++ style namespace separator.

The target UIDs feature of BASIS is quite more sophisticated than what CMake offers out of the box.

**Comment by ahundt** [comment]
ok, didn't know as much about it so I thought the idea was worth consideration. Seems it won't fit, thanks!
