### ISSUE TITLE
Use capital <PKG> name in package variables

### ISSUE THREAD

**Issue by schuhschuh** [schuhschuh/cmake-basis#510]
Since CMake 3, the consensus seems to capitalise all variable names of package configurations regardless of the capitalisation of the package name itself.

- [ ] Update overloaded ```find_package``` in ```CommonTools.cmake```.
- [ ] Modify ```basis_find_package``` and ```basis_use_package```.
- [ ] Update Find modules included in BASIS.

Attention: This change will break backwards compatibility if not variables of either capitalisation are kept for existing Find modules.

**Comment by ahundt** [comment]
I've also found this isn't strictly true for all modules, if I recall correctly boost is one cmake 3.x counterexample.

**Comment by schuhschuh** [comment]
Thanks for the counter example. Because I think I prefer not to make these
changes actually given that they would break backwards compatibility.
